name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022"

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Determine next version
      id: next_version
      shell: pwsh
      run: |
        git fetch --tags
        $latestTag = git describe --tags (git rev-list --tags --max-count=1)
        if (-not $latestTag) {
          $nextTag = "v1.0.0"
        } else {
          $versionParts = $latestTag -split '\.'
          $versionParts[-1] = [int]$versionParts[-1] + 1
          $nextTag = $versionParts -join '.'
        }
        echo "Latest tag: $latestTag"
        echo "Next tag: $nextTag"
        echo "NEXT_TAG=$nextTag" >> $env:GITHUB_ENV

    - name: Create and push tag
      env:
        NEXT_TAG: ${{ env.NEXT_TAG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag $env:NEXT_TAG
        git push origin $env:NEXT_TAG

    - name: Archive Release
      run: |
        $tempDir = New-Item -ItemType Directory -Path build/temp_release
        Copy-Item -Path build/Release/* -Destination $tempDir.FullName -Recurse -Force
        Compress-Archive -Path "$tempDir/*" -DestinationPath build/release.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEXT_TAG }}
        release_name: Release ${{ env.NEXT_TAG }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/release.zip
        asset_name: my_project.zip
        asset_content_type: application/zip
